# action.yaml
name: 'gh-checker-pr-is-updated'
description: 'GitHub Actions check if PR's branch is updated'
inputs:
  remote_branch:
    description: 'Remote branch (e.g.: upstream/main)'
    required: true
    default: 'upstream/main'
  pr_sha:
    description: 'PR SHA'
    required: true

branding:
  icon: check-circle
  color: green

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.remote_branch }}
    - ${{ inputs.pr_sha }}
